language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
before_install:
  - source $TRAVIS_BUILD_DIR/install.sh
script:
  - build_platform esp32
  - build_platform uno
  - build_platform leonardo
  - build_platform zero
  - build_platform esp8266
  - build_platform m4
  - build_platform arcada

notifications:
  email:
    on_success: change
    on_failure: change
