language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    # Caches Arduino IDE + ESP32 platform
    - ~/.arduino15/packages/
    # Caches Arduino platforms
git:
  depth: false
  quiet: true
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.5"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}/install.sh)
script:
  - build_platform esp32
  - build_platform uno
  - build_platform leonardo
  - build_platform zero
  - build_platform esp8266
notifications:
  email:
    on_success: change
    on_failure: change